### HW1 - *NumPy* Basics

(30 pts)

The grading will be based on the simplicity and quality of the code. 

### Objectives
- Using Numpy
- Top-level functions vs Instance methods
- Input and Output methods
- Getting used to learning side topics through provided reference links.

### Note
- Queston marks "?" in code cells are placholders, which may represent multiple lines of code.
- To help you debug the problem. we may have put some sample outpus in the notebook.

### Submission

- Upload both html and ipynb files to Canvas. 


In [2]:
# Load packages needed in this problem set. Don't change this cell.
import math 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Q1 (20 pts) Numpy Basics

<u>***Question 1.1 (pt 1)***</u> :

Convert the following list to a *NumPy* Array.

In [3]:
list_to_convert = [[1, 2, 3], [4, 5, 6]] 
numpy_array = np.array(list_to_convert)
numpy_array 

array([[1, 2, 3],
       [4, 5, 6]])

<u>***Question 1.2 (pt 1)***</u> :

Cast the data in the 'numpy_array' to floating point format in a new array 'float_array'.

In [5]:
float_array = numpy_array.astype(float)
float_array

array([[1., 2., 3.],
       [4., 5., 6.]])

<u>***Question 1.3 (pt 3)***</u> :

Use 3 methods (check our slides) to transpose the 'numpy_array'

In [ ]:
#1 

flip_array = ?
flip_array

In [ ]:
#2

flip_array = ?
flip_array

In [ ]:
#3 
flip_array = ?
flip_array

<u>***Question 1.4 (pt 2)***</u> :

Linear algebra is essential to machine learning algorithms and we will learn most of them in CS334. Here, let's get to know one basic method, inner dot.

Use 2 methods to perform matrix dot between 'numpy_array' and 'flip_array'.

In [ ]:
#1

?

In [ ]:
#2

?

<u>***Question 1.5 (pt 1)***</u> :

Create a 3x4 Array of Zeros.

In [ ]:
zeros_array_3x4 = ?
zeros_array_3x4

<u>***Question 1.6 (pt 1)***</u> :

Create a 4x3 Empty Array.

In [ ]:
empty_array_4x3 = ?
empty_array_4x3

<u>***Question 1.7 (pt 1)***</u> :

Use a *NumPy* function to create an array with all of the odd numbers between 1 and 10, inclusive.  

In [ ]:
odd_vals = ?
odd_vals

<u>***Question 1.8 (pt 1)***</u> :

Use an ndarray method or attribute to find the number of rows and columns in `empty_array_4x3`. 

In [12]:
dims = ?
dims

(4, 3)

<u>***Question 1.9 (pt 2)***</u> :

Use a *NumPy* function to generate a range of values starting at 1 and going to 10, and another function to put these into a 5x2 Array.  

In [ ]:
vals_5x2 = ?
vals_5x2

<u>***Question 1.10 (pt 1)***</u> :

Use an ndarray method or attribute to determine the data type of values in the `empty_array_4x3` array.

In [14]:
data_type = ?
data_type

dtype('float64')

<u>***Question 1.11 (pt 2)***</u> :

Use the following 2 methods from numpy.random module to create a 6x3 array of randomly generated normally distributed values. 

- rng.standard_normal()
- randn()

You should be capable to find their reference page. For example:

https://numpy.org/devdocs/reference/random/generated/numpy.random.Generator.standard_normal.html


In [15]:
# use rng.standard_normal()

?
random_6x3 = ?
random_6x3

array([[-1.42382504,  1.26372846, -0.87066174],
       [-0.25917323, -0.07534331, -0.74088465],
       [-1.3677927 ,  0.6488928 ,  0.36105811],
       [-1.95286306,  2.34740965,  0.96849691],
       [-0.75938718,  0.90219827, -0.46695317],
       [-0.06068952,  0.78884434, -1.25666813]])

In [16]:
# use legacy function randn()

random_6x3 = ?
random_6x3

array([[ 0.51151408,  0.67564812, -0.40882755],
       [ 0.44632171,  0.2559461 ,  1.55720973],
       [-0.54186267, -0.05648434,  0.75273798],
       [-0.15598187, -0.94586536,  0.16221918],
       [-0.051992  , -0.68981585,  0.98524885],
       [-0.89413134,  0.36661062,  1.71139091]])

<u>***Question 1.12 (pt 2)***</u> :

Compare the speed for creating 1 million random numbers using the above 2 methods. 

In [17]:
N = 1_000_1000

In [ ]:
# measure standard_normal()

?

In [ ]:
# measure randn()

?

<u>***Question 1.13. (pt 2)***</u> :

Create a 6x3 Boolean array with `True` values for all of the numbers in the `random_6x3` array that are greater than 1. 

In [20]:
greater_than_1 = ?
greater_than_1

array([[False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True]])

## Q2 (10 pts).  Great Circle (again) using Numpy and a little Pandas


You've already learned the concept of **great circle** and its caclucation using Python's built-in functions and packages. 

Now let's use `Numpy`. Please refer to your solution to the prior assignments (e.g., Lab 2) for calculation details.

**Note: Pandas is a better choice to handel the following example than Numpy. Here we just want to give it a try with Numpy.**


**Preparation**: resue your great_circle function. You can copy it from your lab solution here:

In [21]:
# First, let's difine a function to compute the great circle distance

def great_circle(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """
    Calculate the great-circle distance between two points on the Earth's surface.

    Parameters:
    lat1 (float): Latitude of the first point in degrees.
    lon1 (float): Longitude of the first point in degrees.
    lat2 (float): Latitude of the second point in degrees.
    lon2 (float): Longitude of the second point in degrees.

    Returns:
    float: The great-circle distance between the two points in kilometers.
    """
    
    # Convert latitude and longitude from degrees to radians
    lat1 = ?
    lon1 = ?
    lat2 = ?
    lon2 = ?

    # Calculate the great-circle distance
    ?

    return d

**Q2.1 (2 pts)**: Google the longitude and latitude information for the following cities

Paris, San Francisco, Boise

Create a Numpy's ndarray "data_locations" to hold 3 rows of (latitude, longitude) information for 3 cities: Paris, San Francisco, Boise. 

We expect to use numpy's ndarray "data_locations" to store the numerical parts of the following dataframe: 



|     | Latitude | Longitude|
| --- | --- | --- |
|**Paris**	|48.8575	|2.3514
|**San Francisco** | 37.7749 | -122.4194 |
| **Boise**|	43.6150	|-116.2023




In [22]:
data_location = ?
data_location

array([[  48.8575,    2.3514],
       [  37.7749, -122.4194],
       [  43.615 , -116.2023]])

**Q2.2 (2pts):** Output them into a text file called "locations.txt", where we seperate data points using comma as delimiter.  Here, you need to use the **np.savetxt()** function, please read the reference carefully:

https://numpy.org/doc/2.1/reference/generated/numpy.savetxt.html

Particularly make sure you understand the following syntax:

`numpy.savetxt(fname, X, fmt='%10.4f', delimiter=',', newline='\n', header='', footer='', comments=' ', encoding=None)`

It is worth noting that, numpy.savetxt() can easily handle column names using the header parameter, it does not have a built-in feature for row names. That's why we generally use Pandas to handle both column names and row names. 

Now, let's save the information to the "locations.txt"


In [23]:
# Read the reference to np.savetxt() and use it

?

You can easily view the file using '!' and a Shell command 'cat':

In [24]:
!cat locations.txt

   48.8575,    2.3514
   37.7749, -122.4194
   43.6150, -116.2023


**Q2.3 (2 pts)** Use the np.loadtxt() function to read the `location.txt'. 

https://numpy.org/doc/2.3/reference/generated/numpy.loadtxt.html

Hint: since the delimiter in the locations.txt is comma ',', we have to tell np.loadtxt this info by setting delimiter=','.

In [25]:
array = ?
array

array([[  48.8575,    2.3514],
       [  37.7749, -122.4194],
       [  43.615 , -116.2023]])

**Q2.4 (4 pts)** Use the np.loadtxt() function to read the `location.txt'. 


In [26]:
# let's compute d between Paris and Boise

lat1 = ?
lon1 = ?
lat2 = ?
lon2 = ?

print(f"Latitude and longitude of the first point: ({lat1}, {lon1})")
print(f"Latitude and longitude of the second point: ({lat2}, {lon2})")
print(f"Great-circle distance between the two points: {great_circle(lat1, lon1, lat2, lon2):.3f} km")

Latitude and longitude of the first point: (48.8575, 2.3514)
Latitude and longitude of the second point: (43.615, -116.2023)
Great-circle distance between the two points: 8121.058 km


## **Extended reading**

Again, Pandas is a better choice than Numpy in this case. Let's have some fun and see how to work on the same task using Pandas.

For those who haven't learned Pandas, it is totally fine, we will touch those topics very soon. 

For those who have done Pandas before, see if you can have some better solutions.

In [27]:
# We use Pandas to read the file
# Hint: pay attention to the index (row) names. 

row_names = ['Latitude', 'Longitude']
result = pd.read_csv("locations.txt", names=row_names)
result

Latitude  Longitude
0   48.8575     2.3514
1   37.7749  -122.4194
2   43.6150  -116.2023

In [28]:
# add row names

city_names = ['Paris', 'San Francisco', 'Boise']
result.index = city_names
result

Latitude  Longitude
Paris           48.8575     2.3514
San Francisco   37.7749  -122.4194
Boise           43.6150  -116.2023

In [29]:
# let's compute d between Paris and Boise

lat1 = result.loc['Paris']['Latitude']
lon1 = result.loc['Paris']['Longitude']
lat2 = result.loc['Boise']['Latitude']
lon2 = result.loc['Boise']['Longitude']

print(f"Latitude and longitude of the first point: ({lat1}, {lon1})")
print(f"Latitude and longitude of the second point: ({lat2}, {lon2})")
print(f"Great-circle distance between the two points: {great_circle(lat1, lon1, lat2, lon2):.3f} km")

Latitude and longitude of the first point: (48.8575, 2.3514)
Latitude and longitude of the second point: (43.615, -116.2023)
Great-circle distance between the two points: 8121.058 km
